### PR TITLE
Edit: Use Array instead of a long case

### PR DESCRIPTION
**Pull request by zakariaGatter**
i like your project ots very simple and very useful.

so i check and in its code lines in found some functions that can be improve 

thank you again for this beautiful project

### CODE REVIEW

**Comment by Henryws** [comment]
Could you open this PR in [pacstall/pacstall](https://github.com/pacstall/pacstall) instead of this Termux repo

**Comment by zakariaGatter** [comment]
> Could you open this PR in [pacstall/pacstall](https://github.com/pacstall/pacstall) instead of this Termux repo

i remember you, you are the owner of `pacstall/pacstall` i tried to Contribute in your project but you reject 2 of why `pull requests`, you said you gonna rewrite your project in python insted

**Comment by Henryws** [comment]
Yes, however we're still working on our bash versionn(about to release a new version), and this PR you made looks very clean and useful.

**Comment by zakariaGatter** [comment]
> Yes, however we're still working on our bash version (about to release a new version), and this PR you made looks very clean and useful. And it significantly cuts down on code, instead of just rewriting it, so this has a very high chance of getting merged.

if you want to copy my code and use it, i don't have a problem but i don't feel comfortable contribution to `pacstall/pacstall` code

**Pull request closed without merging**
